name: CI

# when the workflow will run
on:
  push:
    branches: [ master ]
  pull_request:

  # Allows manually starting this workflow from the Actions tab
  workflow_dispatch:

jobs:
  generate-matrix:
    name: "Generate matrix from cabal"
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    runs-on: ubuntu-latest
    steps:
      - name: Extract the tested GHC versions
        uses: kleidukos/get-tested@v0.1.10.0
        id: set-matrix
        with:
          cabal-file: case-insensitive.cabal
          ubuntu-version: "latest"
          macos-version: "latest"
          windows-version: "latest"
          version: 0.1.10.0
  tests:
    name: ${{ matrix.ghc }} on ${{ matrix.os }}
    needs: generate-matrix
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.generate-matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v7

      - name: Set up Haskell
        id: setup-haskell
        uses: haskell-actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: "latest"

      - name: "Cabal: Update cabal package database, generate build plan"
        run: |
          cabal update
          cabal build --dry-run

      - name: Cache
        uses: actions/cache@v6
        with:
          key: ${{ runner.os }}-ghc-${{ matrix.ghc }}-${{ hashFiles('**/plan.json') }}
          path: ${{ steps.setup-haskell.outputs.cabal-store }}
          restore-keys: ${{ runner.os }}-ghc-${{ matrix.ghc }}-

      - name: "Cabal: Build"
        run: cabal build

      - name: "Cabal: Test"
        run: cabal test all --enable-tests

  mhs:
    runs-on: ubuntu-latest
    steps:
      - name: checkout mhs repo
        uses: actions/checkout@v4
        with:
          repository: augustss/MicroHs
          ref: v0.16.0.0
          path: mhs

      - name: make and install mhs
        run: |
          cd mhs
          make minstall

      - name: checkout transformers repo
        uses: actions/checkout@v4
        with:
          path: transformers

      - name: compile and install transformers package
        run: |
          PATH="$HOME/.mcabal/bin:$PATH"
          cd transformers
          mcabal -r install
