name: CI

# when the workflow will run
on:
  push:
    branches: [ master ]
  pull_request:

  # Allows manually starting this workflow from the Actions tab
  workflow_dispatch:

jobs:
  # generate-matrix:
  #   name: "Generate matrix from cabal"
  #   outputs:
  #     matrix: ${{ steps.set-matrix.outputs.matrix }}
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Extract the tested GHC versions
  #       uses: kleidukos/get-tested@v0.1.10.0
  #       id: set-matrix
  #       with:
  #         cabal-file: case-insensitive.cabal
  #         ubuntu-version: "latest"
  #         macos-version: "latest"
  #         windows-version: "latest"
  #         version: 0.1.10.0
  tests:
    name: ${{ matrix.ghc }} on ${{ matrix.os }}
    # needs: generate-matrix
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      # TODO: restore get-tested
      # see https://github.com/basvandijk/case-insensitive/actions/runs/36260084793
      matrix:
        ghc: [ "9.2", "9.4", "9.6", "9.8", "9.10", "9.12", "9.14" ]
        os: [ "ubuntu-latest", "macos-latest", "windows-latest" ]
        include:
          - ghc: "7.10"
            os: "windows-latest"
          - ghc: "8.2"
            os: "windows-latest"
          - ghc: "8.10"
            os: "windows-latest"
          - ghc: "8.0"
            os: "ubuntu-latest"
          - ghc: "8.10"
            os: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v7

      - name: Set up Haskell
        id: setup-haskell
        uses: haskell-actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: "latest"

      - name: "Cabal: Update cabal package database, generate build plan"
        run: |
          cabal update
          cabal build --dry-run

      - name: Cache
        uses: actions/cache@v6
        with:
          key: ${{ runner.os }}-ghc-${{ matrix.ghc }}-${{ hashFiles('**/plan.json') }}
          path: ${{ steps.setup-haskell.outputs.cabal-store }}
          restore-keys: ${{ runner.os }}-ghc-${{ matrix.ghc }}-

      - name: "Cabal: Build"
        run: cabal build

      - name: "Cabal: Test"
        run: cabal test all --enable-tests
